// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Saturn.AzureFunctions")>]
[<assembly: AssemblyProductAttribute("Saturn")>]
[<assembly: AssemblyDescriptionAttribute("Opinionated, web development framework for F# which implements the server-side, functional MVC pattern")>]
[<assembly: AssemblyVersionAttribute("0.10.0")>]
[<assembly: AssemblyFileVersionAttribute("0.10.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Saturn.AzureFunctions"
    let [<Literal>] AssemblyProduct = "Saturn"
    let [<Literal>] AssemblyDescription = "Opinionated, web development framework for F# which implements the server-side, functional MVC pattern"
    let [<Literal>] AssemblyVersion = "0.10.0"
    let [<Literal>] AssemblyFileVersion = "0.10.0"
