// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Saturn.Extensions.Authorization")>]
[<assembly: AssemblyProductAttribute("Saturn")>]
[<assembly: AssemblyDescriptionAttribute("Opinionated, web development framework for F# which implements the server-side, functional MVC pattern")>]
[<assembly: AssemblyVersionAttribute("0.7.3")>]
[<assembly: AssemblyFileVersionAttribute("0.7.3")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Saturn.Extensions.Authorization"
    let [<Literal>] AssemblyProduct = "Saturn"
    let [<Literal>] AssemblyDescription = "Opinionated, web development framework for F# which implements the server-side, functional MVC pattern"
    let [<Literal>] AssemblyVersion = "0.7.3"
    let [<Literal>] AssemblyFileVersion = "0.7.3"
