name: Build

on: [push, pull_request]

jobs:
  build:

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        dotnet: [5.0.100]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Restore tools
      run: dotnet tool restore
    - name: Run Test
      run: dotnet fake build -t Test
